name: faso_carbu_mobile
description: "A new Flutter project."

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.0.0
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  http: ^0.13.6
  mobile_scanner: ^3.5.2
  charts_flutter: ^0.12.0
  sqflite: ^2.2.8+4
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true